In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\\phase_1_project\\data_set\\sms-call-internet-mi-2013-11-07.csv")

In [3]:
df.head(1)

,datetime,CellID,countrycode,smsin,smsout,callin,callout,internet
0,2013-11-07 00:00:00,1,0,0.2463,NaN,NaN,NaN,NaN

In [4]:
df.isnull().sum(
)

datetime             0
CellID               0
countrycode          0
smsin          1492720
smsout         1865924
callin         1727643
callout        1417432
internet       1299270
dtype: int64

In [5]:
df.isnull().mean() * 100

datetime        0.000000
CellID          0.000000
countrycode     0.000000
smsin          62.005895
smsout         77.508366
callin         71.764330
callout        58.878517
internet       53.970202
dtype: float64

In [6]:
# df = df.fillna(0)

In [7]:
df.dtypes

datetime           str
CellID           int64
countrycode      int64
smsin          float64
smsout         float64
callin         float64
callout        float64
internet       float64
dtype: object

In [8]:
# df = df.drop_duplicates()

In [9]:
# df["datetime"] = pd.to_datetime(df["datetime"])
# import datetime
# df["time"] = df["datetime"].dt.time
# df["date"] = df["datetime"].dt.date
# df.drop(columns=["datetime"])

# df.dtypes

In [10]:
mapping = {
    "datetime":"datetime",
    "CellID":"grid_id",
    "countrycode":"country_code",
    "smsin":"sms_in",
    "smsout":"sms_out",
    "callin":"call_in",
    "callout":"call_out",
    "internet":"internet"
}

df_canonical = df.rename(columns=mapping)

df_canonical.dtypes

datetime            str
grid_id           int64
country_code      int64
sms_in          float64
sms_out         float64
call_in         float64
call_out        float64
internet        float64
dtype: object

In [11]:
df_canonical.head(1)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet
0,2013-11-07 00:00:00,1,0,0.2463,NaN,NaN,NaN,NaN

In [12]:
import datetime
df_canonical["datetime"] = pd.to_datetime(df_canonical["datetime"])
print(df_canonical["datetime"].dt.hour.nunique())

24

In [13]:
df_canonical["timestamp"] = df_canonical["datetime"].dt.time
df_canonical["date"] = df_canonical["datetime"].dt.date
df_canonical["hour"] = df_canonical["datetime"].dt.hour + 1
df_canonical["day"] = df_canonical["datetime"].dt.day

df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day
0,2013-11-07,1,0,0.2463,NaN,NaN,NaN,NaN,00:00:00,2013-11-07,1,7
1,2013-11-07,1,39,1.4627,1.6610,0.2999,0.1644,55.8591,00:00:00,2013-11-07,1,7
2,2013-11-07,2,0,0.2467,NaN,NaN,NaN,NaN,00:00:00,2013-11-07,1,7
3,2013-11-07,2,39,1.4768,1.6736,0.3033,0.1648,56.0243,00:00:00,2013-11-07,1,7
4,2013-11-07,3,0,0.2471,NaN,NaN,NaN,NaN,00:00:00,2013-11-07,1,7

In [14]:
df_canonical = df_canonical.drop_duplicates()
df_canonical = df_canonical.fillna(0)

df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day
0,2013-11-07,1,0,0.2463,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7
1,2013-11-07,1,39,1.4627,1.6610,0.2999,0.1644,55.8591,00:00:00,2013-11-07,1,7
2,2013-11-07,2,0,0.2467,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7
3,2013-11-07,2,39,1.4768,1.6736,0.3033,0.1648,56.0243,00:00:00,2013-11-07,1,7
4,2013-11-07,3,0,0.2471,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7

In [15]:
grid_count = (
    df_canonical.groupby(["hour","grid_id"])["country_code"].nunique()
)

print(grid_count)

hour  grid_id
1     1          2
      2          2
      3          2
      4          2
      5          2
                ..
24    9996       8
      9997       6
      9998       6
      9999       6
      10000      6
Name: country_code, Length: 239999, dtype: int64

In [16]:
df_canonical["total_sms"] = df_canonical["sms_in"] + df_canonical["sms_out"]

In [17]:
df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day,total_sms
0,2013-11-07,1,0,0.2463,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2463
1,2013-11-07,1,39,1.4627,1.6610,0.2999,0.1644,55.8591,00:00:00,2013-11-07,1,7,3.1237
2,2013-11-07,2,0,0.2467,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2467
3,2013-11-07,2,39,1.4768,1.6736,0.3033,0.1648,56.0243,00:00:00,2013-11-07,1,7,3.1504
4,2013-11-07,3,0,0.2471,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2471

In [18]:
df_canonical["total_calls"] = df_canonical["call_in"] + df_canonical["call_out"]

In [19]:
df_canonical["total_activity"] = df_canonical["total_calls"] + df_canonical["total_sms"] + df_canonical["internet"]

In [20]:
df_canonical.head(10)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day,total_sms,total_calls,total_activity
0,2013-11-07,1,0,0.2463,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2463,0.0000,0.2463
1,2013-11-07,1,39,1.4627,1.6610,0.2999,0.1644,55.8591,00:00:00,2013-11-07,1,7,3.1237,0.4643,59.4471
2,2013-11-07,2,0,0.2467,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2467,0.0000,0.2467
3,2013-11-07,2,39,1.4768,1.6736,0.3033,0.1648,56.0243,00:00:00,2013-11-07,1,7,3.1504,0.4681,59.6428
4,2013-11-07,3,0,0.2471,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2471,0.0000,0.2471
5,2013-11-07,3,39,1.4918,1.6870,0.3071,0.1652,56.2002,00:00:00,2013-11-07,1,7,3.1788,0.4723,59.8513
6,2013-11-07,4,0,0.2453,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2453,0.0000,0.2453
7,2013-11-07,4,39,1.4218,1.6246,0.2897,0.1634,55.3806,00:00:00,2013-11-07,1,7,3.0464,0.4531,58.8801
8,2013-11-07,5,0,0.2189,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2189,0.0000,0.2189
9,2013-11-07,5,39,1.2681,1.4635,0.2683,0.1449,50.3968,00:00:00,2013-11-07,1,7,2.7316,0.4132,53.5416

In [21]:
unique_grids = df_canonical["grid_id"].nunique()
unique_grids

10000

In [22]:
print(df_canonical["timestamp"].min())
print(df_canonical["timestamp"].max())

00:00:00
23:00:00

In [23]:
df_canonical.dtypes

datetime          datetime64[us]
grid_id                    int64
country_code               int64
sms_in                   float64
sms_out                  float64
call_in                  float64
call_out                 float64
internet                 float64
timestamp                 object
date                      object
hour                       int32
day                        int32
total_sms                float64
total_calls              float64
total_activity           float64
dtype: object

In [24]:
print(df_canonical["timestamp"].nunique())

24

In [25]:
country = df_canonical["country_code"].unique()

In [26]:
busy = (df_canonical.groupby("grid_id")["total_activity"].sum())
busy

grid_id
1        1648.8273
2        1660.2439
3        1672.3949
4        1615.7658
5        1485.5759
           ...
9996     6524.8851
9997     7128.6795
9998     7005.3029
9999     4516.4636
10000    3717.8790
Name: total_activity, Length: 10000, dtype: float64

In [27]:
busy.max()

np.float64(306099.4571)

In [28]:
busy.idxmax()

np.int64(5259)

In [29]:
#cadence
df_canonical["timestamp"].nunique()

24

In [30]:
print(country, len(country))

[    0    39    46    41    43    86    55    33    49    44    82   593
    34    32   212   351    20    45    40   221    63   213    48   353
  1514  1829    54   880    31     1 88239   355  1849   503   242    90
   421   386    61    62   972    53   216    36    57    94    56    51
     7   971   420   352   994   389   358   886   357   381    92    30
    58   372   380    47    81   226   262  1403   961  1647   385  1214
   507   377   370   230   852  1780   238   505   254   598    93   966
    66 18096    52  1705   359   375   591   856   974  1819   218    65
   371  1204   373   237  1416   228   354  1604 18097    98   234    91
   506   225    60   965   258   853   501   590    84   998   243   248
 18094  7778   996 18098    27   220 18093  1579   596   244   599    64
   504  7771  7777   261  7701   964   975  7702  1926   356   250   229
   995   233    95   256  7705   968  1778   252  1787   222   291  1907
  8817   382   245   249   378   374  7707   387   255   251   211   962
   855  1519  7775  1905  7727   960  1613   973  1784 18762   267  7700
   224  1340   376   223   977   423   594   239  1438  1289   241   676
   257   227  1587  1306   235  7712   263 14415   963 18765  1418   231
   687   268   595   672  1924   992 97259 50948  1758  1902 12687 18092
   970   509 14413  1808   993   265  1450   597  1809  1721   232  1242
  1246  8816   266   260 18686   882 18099   350 18683   967 88232 97222
  1226  1250   240 88235  7711   379   976   677   502  1649  1581  1441
   247 88216 18769 18763   689  1709] 258

In [31]:
busy

grid_id
1        1648.8273
2        1660.2439
3        1672.3949
4        1615.7658
5        1485.5759
           ...
9996     6524.8851
9997     7128.6795
9998     7005.3029
9999     4516.4636
10000    3717.8790
Name: total_activity, Length: 10000, dtype: float64

In [32]:
busy.sort_values()[::-1]

grid_id
5259    306099.4571
5059    276329.4901
5258    252354.2746
5159    251119.8461
5061    248586.4882
           ...
5210       184.2108
5310       182.1126
1207       114.3224
112         75.4984
2801        53.4370
Name: total_activity, Length: 10000, dtype: float64

In [33]:
busy_hour = (df_canonical.groupby("hour")["total_activity"].sum())

In [34]:
busy_hour.idxmax()

np.int32(15)

In [35]:

busy.max()

np.float64(306099.4571)

In [36]:
null_count = df.isna().sum()

In [37]:
print(null_count)

datetime             0
CellID               0
countrycode          0
smsin          1492720
smsout         1865924
callin         1727643
callout        1417432
internet       1299270
dtype: int64

In [38]:
df_canonical.columns

Index(['datetime', 'grid_id', 'country_code', 'sms_in', 'sms_out', 'call_in',
       'call_out', 'internet', 'timestamp', 'date', 'hour', 'day', 'total_sms',
       'total_calls', 'total_activity'],
      dtype='str')

In [39]:
df_canonical

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day,total_sms,total_calls,total_activity
0,2013-11-07 00:00:00,1,0,0.2463,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2463,0.0000,0.2463
1,2013-11-07 00:00:00,1,39,1.4627,1.6610,0.2999,0.1644,55.8591,00:00:00,2013-11-07,1,7,3.1237,0.4643,59.4471
2,2013-11-07 00:00:00,2,0,0.2467,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2467,0.0000,0.2467
3,2013-11-07 00:00:00,2,39,1.4768,1.6736,0.3033,0.1648,56.0243,00:00:00,2013-11-07,1,7,3.1504,0.4681,59.6428
4,2013-11-07 00:00:00,3,0,0.2471,0.0000,0.0000,0.0000,0.0000,00:00:00,2013-11-07,1,7,0.2471,0.0000,0.2471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2407379,2013-11-07 23:00:00,10000,7,0.0000,0.0000,0.0000,0.0000,0.0872,23:00:00,2013-11-07,24,7,0.0000,0.0000,0.0872
2407380,2013-11-07 23:00:00,10000,39,4.3872,2.9300,2.6409,0.6442,135.6360,23:00:00,2013-11-07,24,7,7.3172,3.2851,146.2383
2407381,2013-11-07 23:00:00,10000,40,0.0860,0.0000,0.0000,0.0000,0.0000,23:00:00,2013-11-07,24,7,0.0860,0.0000,0.0860
2407382,2013-11-07 23:00:00,10000,216,0.0095,0.0000,0.0000,0.0000,0.0000,23:00:00,2013-11-07,24,7,0.0095,0.0000,0.0095
2407383,2013-11-07 23:00:00,10000,221,0.1720,0.0000,0.0860,0.0860,0.0000,23:00:00,2013-11-07,24,7,0.1720,0.1720,0.3440