In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("D:\\phase_1_project\\data_set\\sms-call-internet-mi-2013-11-01.csv")

In [31]:
df.head(1)

,datetime,CellID,countrycode,smsin,smsout,callin,callout,internet
0,2013-11-01 00:00:00,1,0,0.3521,NaN,NaN,0.0273,NaN

In [32]:
df.isnull().sum(
)

datetime             0
CellID               0
countrycode          0
smsin          1086153
smsout         1422446
callin         1407781
callout        1037413
internet       1087074
dtype: int64

In [33]:
df.isnull().mean() * 100

datetime        0.000000
CellID          0.000000
countrycode     0.000000
smsin          57.409849
smsout         75.184996
callin         74.409861
callout        54.833641
internet       57.458529
dtype: float64

In [34]:
# df = df.fillna(0)

In [35]:
df.dtypes

datetime           str
CellID           int64
countrycode      int64
smsin          float64
smsout         float64
callin         float64
callout        float64
internet       float64
dtype: object

In [36]:
# df = df.drop_duplicates()

In [37]:
# df["datetime"] = pd.to_datetime(df["datetime"])
# import datetime
# df["time"] = df["datetime"].dt.time
# df["date"] = df["datetime"].dt.date
# df.drop(columns=["datetime"])

# df.dtypes

In [38]:
mapping = {
    "datetime":"datetime",
    "CellID":"grid_id",
    "countrycode":"country_code",
    "smsin":"sms_in",
    "smsout":"sms_out",
    "callin":"call_in",
    "callout":"call_out",
    "internet":"internet"
}

df_canonical = df.rename(columns=mapping)

df_canonical.dtypes

datetime            str
grid_id           int64
country_code      int64
sms_in          float64
sms_out         float64
call_in         float64
call_out        float64
internet        float64
dtype: object

In [39]:
df_canonical.head(1)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet
0,2013-11-01 00:00:00,1,0,0.3521,NaN,NaN,0.0273,NaN

In [40]:
import datetime
df_canonical["datetime"] = pd.to_datetime(df_canonical["datetime"])
print(df_canonical["datetime"].dt.hour.nunique())

24

In [41]:
df_canonical["timestamp"] = df_canonical["datetime"].dt.time
df_canonical["date"] = df_canonical["datetime"].dt.date
df_canonical["hour"] = df_canonical["datetime"].dt.hour + 1
df_canonical["day"] = df_canonical["datetime"].dt.day

df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day
0,2013-11-01,1,0,0.3521,NaN,NaN,0.0273,NaN,00:00:00,2013-11-01,1,1
1,2013-11-01,1,33,NaN,NaN,NaN,NaN,0.0261,00:00:00,2013-11-01,1,1
2,2013-11-01,1,39,1.7322,1.1047,0.5919,0.4020,57.7729,00:00:00,2013-11-01,1,1
3,2013-11-01,2,0,0.3581,NaN,NaN,0.0273,NaN,00:00:00,2013-11-01,1,1
4,2013-11-01,2,33,NaN,NaN,NaN,NaN,0.0274,00:00:00,2013-11-01,1,1

In [42]:
df_canonical = df_canonical.drop_duplicates()
df_canonical = df_canonical.fillna(0)

df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day
0,2013-11-01,1,0,0.3521,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1
1,2013-11-01,1,33,0.0000,0.0000,0.0000,0.0000,0.0261,00:00:00,2013-11-01,1,1
2,2013-11-01,1,39,1.7322,1.1047,0.5919,0.4020,57.7729,00:00:00,2013-11-01,1,1
3,2013-11-01,2,0,0.3581,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1
4,2013-11-01,2,33,0.0000,0.0000,0.0000,0.0000,0.0274,00:00:00,2013-11-01,1,1

In [43]:
grid_count = (
    df_canonical.groupby(["hour","grid_id"])["country_code"].nunique()
)

print(grid_count)

hour  grid_id
1     1          3
      2          3
      3          3
      4          3
      5          3
                ..
24    9996       6
      9997       5
      9998       5
      9999       6
      10000      6
Name: country_code, Length: 240000, dtype: int64

In [44]:
df_canonical["total_sms"] = df_canonical["sms_in"] + df_canonical["sms_out"]

In [45]:
df_canonical.head(5)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day,total_sms
0,2013-11-01,1,0,0.3521,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3521
1,2013-11-01,1,33,0.0000,0.0000,0.0000,0.0000,0.0261,00:00:00,2013-11-01,1,1,0.0000
2,2013-11-01,1,39,1.7322,1.1047,0.5919,0.4020,57.7729,00:00:00,2013-11-01,1,1,2.8369
3,2013-11-01,2,0,0.3581,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3581
4,2013-11-01,2,33,0.0000,0.0000,0.0000,0.0000,0.0274,00:00:00,2013-11-01,1,1,0.0000

In [46]:
df_canonical["total_calls"] = df_canonical["call_in"] + df_canonical["call_out"]

In [47]:
df_canonical["total_activity"] = df_canonical["total_calls"] + df_canonical["total_sms"] + df_canonical["internet"]

In [48]:
df_canonical.head(10)

,datetime,grid_id,country_code,sms_in,sms_out,call_in,call_out,internet,timestamp,date,hour,day,total_sms,total_calls,total_activity
0,2013-11-01,1,0,0.3521,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3521,0.0273,0.3794
1,2013-11-01,1,33,0.0000,0.0000,0.0000,0.0000,0.0261,00:00:00,2013-11-01,1,1,0.0000,0.0000,0.0261
2,2013-11-01,1,39,1.7322,1.1047,0.5919,0.4020,57.7729,00:00:00,2013-11-01,1,1,2.8369,0.9939,61.6037
3,2013-11-01,2,0,0.3581,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3581,0.0273,0.3854
4,2013-11-01,2,33,0.0000,0.0000,0.0000,0.0000,0.0274,00:00:00,2013-11-01,1,1,0.0000,0.0000,0.0274
5,2013-11-01,2,39,1.7334,1.0880,0.6020,0.4109,57.8875,00:00:00,2013-11-01,1,1,2.8214,1.0129,61.7218
6,2013-11-01,3,0,0.3644,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3644,0.0273,0.3917
7,2013-11-01,3,33,0.0000,0.0000,0.0000,0.0000,0.0287,00:00:00,2013-11-01,1,1,0.0000,0.0000,0.0287
8,2013-11-01,3,39,1.7348,1.0701,0.6128,0.4203,58.0095,00:00:00,2013-11-01,1,1,2.8049,1.0331,61.8475
9,2013-11-01,4,0,0.3349,0.0000,0.0000,0.0273,0.0000,00:00:00,2013-11-01,1,1,0.3349,0.0273,0.3622

In [49]:
unique_grids = df_canonical["grid_id"].nunique()
unique_grids

10000

In [59]:
df_canonical["timestamp"].min()
df_canonical["timestamp"].max()
print(df_canonical["day"].duplicated().sum())

1891927

In [56]:
df_canonical.dtypes

datetime          datetime64[us]
grid_id                    int64
country_code               int64
sms_in                   float64
sms_out                  float64
call_in                  float64
call_out                 float64
internet                 float64
timestamp                 object
date                      object
hour                       int32
day                        int32
total_sms                float64
total_calls              float64
total_activity           float64
dtype: object

In [58]:
print(df_canonical["timestamp"].nunique())

24